# domain related constants
dataset_type: mnist
image_type: gray

# train settings
batch_size: 256
num_workers: 16
num_epochs: 500
num_timesteps: 1000
main_device: cuda:0
val_freq: 1

# hyper parameters
timestep_encoded_dim: 100
lr: 1.e-3
